const nav=document.querySelector('.nav');
const reveals=document.querySelectorAll('section,.card,.work');
window.addEventListener('scroll',()=>nav?.classList.toggle('scrolled',window.scrollY>30),{passive:true});
const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('reveal','show');observer.unobserve(entry.target)}})},{threshold:.12});
reveals.forEach(el=>observer.observe(el));
const hero=document.querySelector('.hero');
const orb=document.querySelector('.orb');
hero?.addEventListener('pointermove',e=>{const x=(e.clientX/window.innerWidth-.5)*2;const y=(e.clientY/window.innerHeight-.5)*2;if(orb)orb.style.transform=`translate(${x*18}px,${y*12}px) scale(1.02)`});
hero?.addEventListener('pointerleave',()=>{if(orb)orb.style.transform=''});

// Mobile safety layer: keep the hero and Windows 11 navigation inside the viewport.
const mobileStyle=document.createElement('style');
mobileStyle.textContent='html,body{max-width:100%;overflow-x:hidden!important}img,svg{max-width:100%}@media(max-width:760px){.hero{width:100%!important;min-height:100svh!important;padding:90px 16px 120px!important;overflow:hidden!important}.hero>div:not(.orb){width:100%!important;max-width:100%!important;min-width:0!important}.hero .orb{width:280px!important;height:280px!important;max-width:75vw!important;max-height:75vw!important;left:50%!important;top:50%!important;transform:translate(-50%,-50%)!important}.sigil.profile-avatar{width:104px!important;height:104px!important;min-width:104px!important;max-width:104px!important;border-radius:50%!important;overflow:hidden!important;margin:0 auto 24px!important}.sigil.profile-avatar img{display:block!important;width:100%!important;height:100%!important;max-width:none!important;object-fit:cover!important}.hero h1{font-size:clamp(34px,10.5vw,50px)!important;letter-spacing:2px!important;line-height:1.05!important}.hero h2{font-size:10px!important;letter-spacing:4px!important;line-height:1.5!important}.tag{max-width:340px!important;width:100%!important;font-size:14px!important;line-height:1.7!important}.wrap{width:calc(100% - 32px)!important;max-width:100%!important}.profile{grid-template-columns:1fr!important;gap:28px!important}.profile-photo-wrap{width:270px!important;max-width:90vw!important;height:330px!important;margin:auto!important}.profile-photo{width:240px!important;height:290px!important}.profile-ring{width:260px!important;height:315px!important}.grid,.works,.books{grid-template-columns:1fr!important}.nav{left:8px!important;right:8px!important;bottom:8px!important;top:auto!important;transform:none!important;width:calc(100% - 16px)!important;max-width:none!important;padding:6px 5px!important}.navin{width:100%!important;gap:3px!important}.brand{width:34px!important;height:34px!important;min-width:34px!important;flex:0 0 34px!important;padding:6px!important}.windows-logo{width:20px!important;height:20px!important;display:grid!important;grid-template-columns:1fr 1fr!important;grid-template-rows:1fr 1fr!important;gap:2px!important;transform:none!important}.windows-logo i{width:auto!important;height:auto!important;display:block!important;transform:none!important}.links{width:auto!important;min-width:0!important;flex:1 1 auto!important;display:flex!important;gap:1px!important}.links a{width:auto!important;min-width:0!important;flex:1 1 0!important;display:flex!important;align-items:center!important;justify-content:center!important;padding:7px 2px!important;gap:2px!important;font-size:8px!important;line-height:1!important;white-space:nowrap!important;overflow:hidden!important}.links a .win-icon{width:13px!important;height:13px!important;min-width:13px!important;flex:0 0 13px!important}.links a:last-child{font-size:8px!important}}
';
document.head.appendChild(mobileStyle);
